[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "dist-sys-challenge"
version = "0.1.0"
description = "Solution to the Fly.io Distributed Systems Challenge (Maelstrom)"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
authors = [
  {name = "natalka1122"},
]

dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
namespaces = false

[tool.black]
line-length = 100
target-version = ["py314"]

[tool.mypy]
python_version = "3.14"
strict = true
check_untyped_defs = true
follow_untyped_imports = true
mypy_path = ["src"]
exclude = [".mypy_cache/"]

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]